### ISSUE TITLE
Стриймовете не тръгват от днес

### ISSUE THREAD

**Issue by ista** [bokobokoboko/plugin.video.mytvbg#4]
Сякаш са променили нещо на страницата и плъгина вече не работи за съжаление. Поне на мен http://mytv.bg/player_config/config.js не ми се отваря. Може би там е проблемът:

~$ wget http://mytv.bg/player_config/config.js
--2015-04-30 23:29:30--  http://mytv.bg/player_config/config.js
Resolving mytv.bg (mytv.bg)... 144.76.67.146
Connecting to mytv.bg (mytv.bg)|144.76.67.146|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-04-30 23:29:31 ERROR 404: Not Found.

**Comment by bokobokoboko** [comment]
Да. променили са страницата

**Comment by ista** [comment]
Има ли шанс да се коригира лесно или промените са прекалено сериозни?

**Comment by bokobokoboko** [comment]
Zdravei,

nimam nmogo vreme v momenta za da go debagna kakto triabva.

na prav pogled mi se struva che nese e promenila strukturata na 
stranicata i saotvetno url na streema

zastoto kakto ste vidish ot screen shota stringovete koito tarsiam sa si 
tam.

tova koeto mi se struva che se e promenilo e nachina za otorizacia kam 
strem servera.


....

marzi me da pisha

dai nekav telefon da si govorim - moga da zvania pochti v ciala evropa 
bezplatno

skype viber whatsapp hangsout sasto ste svarshat rabota

**Comment by hestan** [comment]
Коригирах проблема, в крайна сметка промята е била много малка. Виж пул рикуеста от преди малко.

**Comment by hestan** [comment]
Оказа се, че мога да мърджвам самият аз! :) Проблемът (засега) е решен!

**Comment by bokobokoboko** [comment]
Супер :)
Както е трагнало не искате ли да направим и нещата от TODO списака:

Not supported functions (TODO list)
 1. Recorded show programs - http://mytv.bg/broadcasts
 2. News - http://mytv.bg/news
 3. Flexable time shifts with minutes precision
 4. Full TV program for all TV chanels - http://mytv.bg/tv_program
